-- ============================================================================
-- POLI - Complete Database Schema
-- ============================================================================
-- This script creates all necessary database structures for POLI AI Assistant
-- Features: Address verification, Trip costs, Route optimization, Holiday alerts
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. ADDRESS VERIFICATION (Clients Table)
-- ----------------------------------------------------------------------------
-- Allows POLI to track which client addresses have been verified/optimized
-- This prevents re-analyzing the same clients, saving API calls

ALTER TABLE clients 
ADD COLUMN IF NOT EXISTS address_verified BOOLEAN DEFAULT false;

ALTER TABLE clients 
ADD COLUMN IF NOT EXISTS address_verified_at TIMESTAMPTZ;

COMMENT ON COLUMN clients.address_verified IS 'Indicates if the client address has been verified/optimized by POLI AI';
COMMENT ON COLUMN clients.address_verified_at IS 'Timestamp when the address was last verified by POLI AI';

-- Index for faster queries
CREATE INDEX IF NOT EXISTS idx_clients_address_verified ON clients(address_verified);

-- ----------------------------------------------------------------------------
-- 2. TRIP COSTS (Tasks Table)
-- ----------------------------------------------------------------------------
-- Allows tracking trip costs for budget management and historical analysis

ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS trip_cost DECIMAL(10,2);

ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS trip_cost_currency VARCHAR(3) DEFAULT 'USD';

COMMENT ON COLUMN tasks.trip_cost IS 'Cost of the trip/travel (optional, can be filled after trip completion)';
COMMENT ON COLUMN tasks.trip_cost_currency IS 'Currency code for trip cost (USD, BRL, ARS, etc.)';

-- ----------------------------------------------------------------------------
-- 3. POLI SUGGESTIONS TABLE
-- ----------------------------------------------------------------------------
-- Central table to store all POLI suggestions across different features
-- Types: route_optimization, trip_cost_reminder, holiday_alert, etc.

CREATE TABLE IF NOT EXISTS poli_suggestions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    type VARCHAR(50) NOT NULL,
    -- Suggestion types:
    -- 'route_optimization' - Suggests visiting nearby clients
    -- 'trip_cost_reminder' - Reminds to fill trip cost
    -- 'holiday_alert' - Warns about holidays on travel dates
    -- 'task_stalled' - Alerts about tasks without updates
    -- 'client_inactive' - Alerts about clients without recent contact
    
    task_id UUID REFERENCES tasks(id) ON DELETE CASCADE,
    client_id UUID REFERENCES clients(id) ON DELETE CASCADE,
    
    title TEXT NOT NULL,
    description TEXT,
    
    -- JSON data specific to each suggestion type
    -- Examples:
    -- route_optimization: { "nearby_clients": [...], "distance_km": 50 }
    -- holiday_alert: { "holiday_name": "Carnaval", "country": "BR" }
    data JSONB,
    
    priority VARCHAR(20) DEFAULT 'medium',
    -- 'critical' - Red, requires immediate attention
    -- 'high' - Orange, important
    -- 'medium' - Yellow, should review
    -- 'low' - Blue, informational
    
    status VARCHAR(20) DEFAULT 'pending',
    -- 'pending' - Waiting for user action
    -- 'accepted' - User accepted the suggestion
    -- 'ignored' - User dismissed the suggestion
    -- 'expired' - Suggestion no longer relevant
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    resolved_at TIMESTAMPTZ,
    resolved_by UUID REFERENCES users(id),
    
    -- Metadata
    created_by_poli BOOLEAN DEFAULT true,
    auto_expire_at TIMESTAMPTZ
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_poli_suggestions_status ON poli_suggestions(status);
CREATE INDEX IF NOT EXISTS idx_poli_suggestions_type ON poli_suggestions(type);
CREATE INDEX IF NOT EXISTS idx_poli_suggestions_task ON poli_suggestions(task_id);
CREATE INDEX IF NOT EXISTS idx_poli_suggestions_client ON poli_suggestions(client_id);
CREATE INDEX IF NOT EXISTS idx_poli_suggestions_created ON poli_suggestions(created_at DESC);

-- Comments
COMMENT ON TABLE poli_suggestions IS 'Stores all suggestions generated by POLI AI Assistant';
COMMENT ON COLUMN poli_suggestions.type IS 'Type of suggestion (route_optimization, trip_cost_reminder, holiday_alert, etc.)';
COMMENT ON COLUMN poli_suggestions.data IS 'JSON data specific to the suggestion type';
COMMENT ON COLUMN poli_suggestions.priority IS 'Priority level: critical, high, medium, low';
COMMENT ON COLUMN poli_suggestions.status IS 'Status: pending, accepted, ignored, expired';

-- ----------------------------------------------------------------------------
-- 4. HELPER FUNCTIONS
-- ----------------------------------------------------------------------------

-- Function to auto-expire old suggestions
CREATE OR REPLACE FUNCTION expire_old_poli_suggestions()
RETURNS void AS $$
BEGIN
    UPDATE poli_suggestions
    SET status = 'expired'
    WHERE status = 'pending'
    AND auto_expire_at IS NOT NULL
    AND auto_expire_at < NOW();
END;
$$ LANGUAGE plpgsql;

-- Function to clean up old resolved suggestions (optional, run manually)
CREATE OR REPLACE FUNCTION cleanup_old_poli_suggestions(days_old INTEGER DEFAULT 90)
RETURNS INTEGER AS $$
DECLARE
    deleted_count INTEGER;
BEGIN
    DELETE FROM poli_suggestions
    WHERE status IN ('accepted', 'ignored', 'expired')
    AND resolved_at < NOW() - (days_old || ' days')::INTERVAL;
    
    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;

-- ----------------------------------------------------------------------------
-- 5. SAMPLE DATA (Optional - for testing)
-- ----------------------------------------------------------------------------

-- Uncomment to insert sample suggestion for testing:
/*
INSERT INTO poli_suggestions (type, title, description, priority, data)
VALUES (
    'route_optimization',
    'Otimização de Rota - São Paulo',
    'Você tem viagem para São Paulo em 25/01. Há 2 clientes próximos sem visita há 60 dias.',
    'medium',
    '{"nearby_clients": ["Cliente A", "Cliente B"], "distance_km": 15}'::jsonb
);
*/

-- ----------------------------------------------------------------------------
-- EXECUTION SUMMARY
-- ----------------------------------------------------------------------------
-- ✅ Added address_verified fields to clients table
-- ✅ Added trip_cost fields to tasks table  
-- ✅ Created poli_suggestions table for all POLI features
-- ✅ Created helper functions for maintenance
-- ✅ Added indexes for performance
-- ✅ Added comprehensive comments

-- Next steps:
-- 1. Execute this script in Supabase SQL Editor
-- 2. Verify tables were created: SELECT * FROM poli_suggestions LIMIT 1;
-- 3. Test POLI features in the app

SELECT 'POLI Database Schema created successfully! ✅' AS status;
